# Generated by Django 2.2.6 on 2020-01-30 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200130_1532'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teamcreation',
            old_name='group',
            new_name='team_name',
        ),
        migrations.RemoveField(
            model_name='teamcreation',
            name='email_alias',
        ),
        migrations.AddField(
            model_name='teamcreation',
            name='team_key',
            field=models.CharField(default='enter a key others can use to join', max_length=100),
        ),
    ]
