# Generated by Django 2.2.6 on 2020-01-31 19:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0005_auto_20200130_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamcreation',
            name='author',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teamcreation',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='teamcreation',
            name='team_key',
            field=models.CharField(default='enter a unique key', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='teamcreation',
            name='team_name',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
