# Generated by Django 2.2.6 on 2020-01-31 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200131_1451'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teamcreation',
            old_name='team_key',
            new_name='group_id',
        ),
    ]
