# Generated by Django 2.2.6 on 2020-01-31 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20200131_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamcreation',
            name='group_id',
        ),
        migrations.RemoveField(
            model_name='teamcreation',
            name='members',
        ),
    ]
