# Generated by Django 2.2.6 on 2020-01-31 20:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0010_auto_20200131_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamcreation',
            name='group_id',
            field=models.IntegerField(default='', max_length=6),
        ),
        migrations.AddField(
            model_name='teamcreation',
            name='members',
            field=models.ManyToManyField(default='', related_name='Members', to=settings.AUTH_USER_MODEL),
        ),
    ]
