# Generated by Django 2.2.6 on 2020-01-31 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_teamcreation_group_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamcreation',
            name='members',
        ),
    ]
