# Generated by Django 2.2.6 on 2020-01-31 21:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_remove_teamcreation_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamcreation',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='teamcreation',
            name='team_name',
            field=models.CharField(default=None, max_length=100, unique=True),
        ),
    ]
