# Generated by Django 2.2.6 on 2020-02-05 20:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0014_auto_20200131_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamcreation',
            name='members',
            field=models.ManyToManyField(default='', related_name='Members', to=settings.AUTH_USER_MODEL),
        ),
    ]
