# Generated by Django 2.2.6 on 2020-02-07 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20200207_1141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamcreation',
            name='team_key',
        ),
        migrations.AddField(
            model_name='teamcreation',
            name='team_k',
            field=models.TextField(default='enter a team key', max_length=80),
        ),
    ]
