# Generated by Django 2.2.6 on 2020-02-07 21:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0018_auto_20200207_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='team_num1',
            field=models.ManyToManyField(default='blank', related_name='Team', to=settings.AUTH_USER_MODEL),
        ),
    ]
