# Generated by Django 2.2.6 on 2020-02-10 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_profile_team_num1'),
    ]

    operations = [
        migrations.CreateModel(
            name='JoinForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(default=None, max_length=100)),
                ('team_k', models.TextField(default='enter a team key', max_length=80)),
            ],
        ),
    ]
