# Generated by Django 2.2.6 on 2020-02-11 19:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_joinform'),
    ]

    operations = [
        migrations.CreateModel(
            name='Join',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(default=None, max_length=100)),
                ('team_k', models.TextField(default='enter a team key', max_length=80)),
            ],
        ),
        migrations.DeleteModel(
            name='JoinForm',
        ),
        migrations.AlterField(
            model_name='profile',
            name='team_num1',
            field=models.ManyToManyField(default='--none', related_name='Team', to=settings.AUTH_USER_MODEL),
        ),
    ]
