# Generated by Django 2.2.6 on 2020-02-11 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20200211_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='team_num1',
        ),
        migrations.AddField(
            model_name='profile',
            name='team_num1',
            field=models.CharField(default='--none', max_length=100),
        ),
    ]
