# Generated by Django 2.2.6 on 2020-02-11 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_auto_20200211_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='team_num1',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
