# Generated by Django 2.2.6 on 2020-02-12 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_auto_20200211_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='team_num1',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
