# Generated by Django 2.2.6 on 2020-02-22 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_auto_20200221_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamcreation',
            name='no_members',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
