# Generated by Django 2.2.6 on 2020-03-18 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_teamcreation_no_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='testusercustomtitle',
            field=models.CharField(default='', max_length=30),
        ),
    ]
