# Generated by Django 2.2.6 on 2020-03-20 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_profile_testusercustomtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='completed_a_test',
            field=models.BooleanField(default=False),
        ),
    ]
