# Generated by Django 2.2.6 on 2020-03-24 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_profile_completed_a_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='areawork',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='aspirations',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='completed_my_goals',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='experience',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
