# Generated by Django 2.2.6 on 2020-04-16 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_auto_20200324_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='completed_a_test',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='completed_my_goals',
        ),
        migrations.AddField(
            model_name='profile',
            name='d_accessdata',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='d_makeemail',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='d_uploaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='g_completedaily',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='g_preferences',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='g_setgoal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='t_improve',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='t_maketest',
            field=models.BooleanField(default=False),
        ),
    ]
