# Generated by Django 2.2.6 on 2020-04-22 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_auto_20200416_1713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamcreation',
            name='author',
        ),
        migrations.RemoveField(
            model_name='teamcreation',
            name='members',
        ),
        migrations.RemoveField(
            model_name='teamcreation',
            name='no_members',
        ),
    ]
